overlay 同步ubuntu20.04分支修改

diff --git a/overlay/usr/bin/resize-helper b/overlay/usr/bin/resize-helper
--- a/overlay/usr/bin/resize-helper
+++ b/overlay/usr/bin/resize-helper
@@ -1,60 +1,61 @@
 #!/bin/sh
-# Copyright (c) Fathi Boudra <fathi.boudra@linaro.org>
-# All rights reserved.
-# 
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions
-# are met:
-# 1. Redistributions of source code must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright
-#    notice, this list of conditions and the following disclaimer in the
-#    documentation and/or other materials provided with the distribution.
-# 
-# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
-# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
-# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
-# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
-# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
-# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
-# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
-# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
-# SUCH DAMAGE.
+### BEGIN INIT INFO
+# Provides:       resize-all
+# Default-Start:  S
+# Default-Stop:
+# Description:    Resize all internal mounted partitions
+### END INIT INFO
 
-# we must be root
-[ $(whoami) = "root" ] || { echo "E: You must be root" && exit 1; }
+# Don't exit on error status
+set +e
 
-# we must have few tools
-SGDISK=$(which sgdisk) || { echo "E: You must have sgdisk" && exit 1; }
-PARTED=$(which parted) || { echo "E: You must have parted" && exit 1; }
-PARTPROBE=$(which partprobe) || { echo "E: You must have partprobe" && exit 1; }
-RESIZE2FS=$(which resize2fs) || { echo "E: You must have resize2fs" && exit 1; }
+# Uncomment below to see more logs
+# set -x
 
-# find root device
-ROOT_DEVICE=$(findmnt --noheadings --output=SOURCE / | cut -d'[' -f1)
-# prune root device (for example UUID)
-ROOT_DEVICE=$(realpath ${ROOT_DEVICE})
-# get the partition number and type
-PART_ENTRY_NUMBER=$(udevadm info --query=property --name=${ROOT_DEVICE} | grep '^ID_PART_ENTRY_NUMBER=' | cut -d'=' -f2)
+. $(dirname $0)/disk-helper
 
-# in case the root device is not on a partitioned media
-if [ "x$PART_ENTRY_NUMBER" = "x" ]; then
-	${RESIZE2FS} "${ROOT_DEVICE}"
-	exit 0
-fi
+LOGFILE=/tmp/resize-all.log
 
-PART_TABLE_TYPE=$(udevadm info --query=property --name=${ROOT_DEVICE} | grep '^ID_PART_TABLE_TYPE=' | cut -d'=' -f2)
-# find the block device
-DEVICE=$(udevadm info --query=path --name=${ROOT_DEVICE} | awk -F'/' '{print $(NF-1)}')
-DEVICE="/dev/${DEVICE}"
+do_part()
+{
+	DEV=$1
+	MOUNT_POINT=$2
+	FSTYPE=$3
+	OPTS=$4
 
-if [ "$PART_TABLE_TYPE" = "gpt" ]; then
-	${SGDISK} -e ${DEVICE}
-	${PARTPROBE}
-fi
+	echo "Handling $DEV $MOUNT_POINT $FSTYPE $OPTS"
 
-${PARTED} ${DEVICE} resizepart ${PART_ENTRY_NUMBER} 100%
-${PARTPROBE}
-${RESIZE2FS} "${ROOT_DEVICE}"
+	# Setup check/mount tools and do some prepare
+	prepare_part || return
+
+	# Store ro/rw
+	MOUNTED_RO_RW=$(touch $MOUNT_POINT &>/dev/null && echo rw || echo ro)
+
+	# Resize partition if needed
+	resize_part
+
+	# Restore ro/rw
+	remount_part $MOUNTED_RO_RW
+}
+
+resize_all()
+{
+	echo "Will now resize all partitions in /proc/mounts"
+
+	while read LINE;do
+		do_part $LINE
+	done < /proc/mounts
+}
+
+case "$1" in
+	start|"")
+		resize_all 2>&1 | tee $LOGFILE
+		echo "Log saved to $LOGFILE"
+		;;
+	*)
+		echo "Usage: resize-helper start" >&2
+		exit 3
+		;;
+esac
+
+:
